### ISSUE TITLE
Issue with a FeedRateNotDefinedException popping up after reseting the simulation

### ISSUE THREAD

**Issue by josip-mrdeza** [josip-mrdeza/PyroNc#39]
This shouldn't be happening, but is probably due to us using JOG to move the tool to begin_point after sim reset.

**Comment by ForsakenNydoseth** [comment]
Fixed one instance of this issue, occurring while the executing of the FOR LOOP is taking place, which used to run all contained commands for an x amount of times (or before causing an error), meanwhile not checking if the simulation has been reset or not, causing the feed rate to be set to 0 when reset and the next G0/G1 derivate command causing an exception (error) because the feed rate is 0, which is ILLEGAL and INVALID.

**Comment by josip-mrdeza** [comment]
This issue has been fixed by removing all elements from the command and FOR LOOP queue before the actual reset and hard stop of the working commands occurs. The issue was present because the next command would automatically try to execute but since all the simulation parameters have been reset the FeedRateNotDefinedException error would occur, signaling that the Feed Rate is currently set to 0.
